### ISSUE TITLE
reloading requirejs

### ISSUE THREAD

**Issue by ORESoftware** [lddubeau/requirejs-reload#1]
hey Sr. Louis

I saw your answer on SO here:
http://stackoverflow.com/questions/19966133/how-to-reload-a-file-via-require-js-triggered-from-the-browsers-js-console

I saw a video of some folks doing hot-reloading with React + Webpack. Thought it could possible with RequireJS, at least with views (not stores).

I have a question though. Say I reload all the .js files for a view.
I assume I would have to call .render() again after loading the views (whether react or backbone) so that the html in the view is actually updated, right? If I don't call render(), nothing visible will happen, right?

The nice thing about all this is it avoids refreshing the page and losing state.

It would be really cool if you could describe a detailed step-by-step workflow on how this functionality is intended to be used. 

I will make an attempt here and now, please correct me:

(1) make a globally defined (window.reload) function that will take arguments in the form of paths to files
(2) create some mechanism to invoke that function given an event (a button that gets clicked)*
(3) you click that button and the reload function will undef the current files and then request those files from the server and put the new files in the same places as the old files
(4) you will need some further action to actually show the difference between the old and new JS, and think that means you will have to call .render() again

can you please correct this? thanks!

**Comment by ORESoftware** [comment]
some more new info. As regards (4) - with views (whether React or Backbone or whatever) it's not enough to load view files then call .render(). Seems like you have to load the file, then create a new instance of the view with the same data sources that originally populated it, then call render. The middle step might be tricky.

**Comment by lddubeau** [comment]
The devil is in the details. I've not yet used Backbone or React so I don't know the details of their operation. 

Yes, whatever function does the rendering would have to be called again after reloading, but whether you'd have to do it explicitly or either Backbone or React would do it automatically and perform the render action properly, given that the DOM has already been altered, is unknown to me. I can imagine framework implementations where everything would work fine, and implementations where things would break.

There is one general issue that could throw a monkey wrench in the whole idea, and again whether this would be a deal breaker depends on details I do not know. The problem is that if you reload a module, **it does not automatically update references to the old module that was previously loaded.** So if the framework you use stores references internally and you cannot somehow refresh these references by yourself, then you are stuck because the framework will still refer to the pre-reload modules.

This is about as much as I can say.

**Comment by ORESoftware** [comment]
yeah that makes sense. I am working on something with Backbone + React + RequireJS. I think it will work. Will let you know what I come up with.
